accounts/urls.py
from django.contrib.auth.signals import user_logged_out
from django.contrib import messages
from django.dispatch import receiver
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^login$', 'django.contrib.auth.views.login', {
        'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {
        'next_page': 'accounts:login'}, name='logout'),
)

@receiver(user_logged_out)
def user_logout_handler(sender, request, **kwargs):
    messages.info(request, "You have logged out.")

favs/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('favs.views',
    url(r'^add-or-remove$', 'add_or_remove',name='add_or_remove'),
    url(r'^add$', 'add',name='add'),
    url(r'^remove$', 'remove', name='remove'),
)

ml/urls.py
from django.conf.urls import patterns, url

from views import *
# build_model, build_model_adhoc, use_model, view_model, index

urlpatterns = patterns('',
                       url(r'^api/ml/build/(?P<ml_id>\d+)/$',
                           build_model, name='build_model'),
                       url(r'^api/ml/build/$',
                           build_model_adhoc, name='build_model_adhoc'),
                       url(r'^api/ml/(?P<ml_id>\d+)/use/$',
                           use_model, name='use_model'),
                       url(r'^/ml/(?P<ml_id>\d+)$',
                           view_model, name='view_model'),
                       url(r'^ml/',
                           index, name='index')
                       )

sqlviz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# from django.views.generic.base import RedirectView
from django.conf import settings

admin.site.site_header = 'SQLViz Admin'
admin.site.index_title = ''


urlpatterns = patterns(
    '',
    url(r'^', include('website.urls', namespace='website')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^favs/', include('favs.urls', namespace='favs')),
    url(r'^explorer/', include('table_explorer.urls')),
    url(r'^', include('ml.urls', namespace='ml')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^search/', include('haystack.urls'), name='haystack_search'),
)


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        'django.views.static',
        (
            r'media/(?P<path>.*)',
            'serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

website/urls.py
from django.conf.urls import patterns, url
#from django.contrib.auth.decorators import login_required, permission_required

from views import *

urlpatterns = patterns('',
                       url(r'^$', index, name='home'),
                       url(r'^api/query/(?P<query_id>\d+)$',
                           query_api, name='query_api'),
                       url(r'^query/(?P<query_ids>[,\d]+)$',
                           query_view, name='query'),
                       url(r'^query/(?P<query_names>[,\w ]+)$',
                           query_name, name='query_name'),
                       url(r'^dashboard/(?P<dashboard_id>\d+)$',
                           dashboard, name='dashboard'),
                       url(r'^filter/', index, name='filter'),
                       url(r'^query_interactive/', query_interactive,
                           name='query_interactive'),
                       url(r'^api/query_interactive/', query_interactive_api,
                           name='query_interactive_api'),
                       url(r'^api/database_explorer/', database_explorer_api,
                           name='database_explorer_api'),
                       )

website/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.template import RequestContext
from django.contrib.auth.models import User
from django.db.models import Q
from itertools import chain

import json
import time
import logging
import traceback

import favit.models
import query
import models
import sql_manager

from ml.models import machine_learning_model
from date_time_encoder import DateTimeEncoder

logger = logging.getLogger(__name__)


@login_required
def index(request):
    query_list = models.Query.objects.filter(hide_index=0)
    dashboard_list = models.Dashboard.objects.filter(hide_index=0)

    # Get Favorites
    user = User.objects.get(username=request.user)
    query_favorites = favit.models.Favorite.objects.\
        for_user(user, model=models.Query)
    query_fav_dict = {}
    query_fav_dict = dict([(i.target_object_id, i) for i in query_favorites])
    query_list_images = []
    for q in query_list:
        if q.id in query_fav_dict:
            setattr(q, 'fav', True)
        else:
            setattr(q, 'fav', False)
        if q.image is not None and q.image != '':
            logging.warning(q)
            #logging.warning(q.image)
            query_list_images.append(q)

    dash_favorites = favit.models.Favorite.objects.\
        for_user(user, model=models.Dashboard)
    dash_fav_dict = dict([(i.target_object_id, i) for i in dash_favorites])

    for d in dashboard_list:
        if d.id in dash_fav_dict:
            setattr(d, 'fav', True)
        else:
            setattr(d, 'fav', False)

    return render_to_response(
        'website/index.html',
        {
            'query_list': query_list,
            'query_list_images': query_list_images,
            'dashboard_list': dashboard_list,
            'query_favorites': query_fav_dict
        },
        context_instance=RequestContext(request))


@login_required
def query_api(request, query_id):
    try:
        start_time = time.time()
        lq = query.LoadQuery(
            query_id=query_id,
            user=request.user,
            parameters=request.GET.dict(),
            cacheable=request.GET.get('cacheable', None)
        )
        q = lq.prepare_query()
        q.run_query()
        q.run_manipulations()
        response_data = q.data_array
        time_elapsed = time.time() - start_time
        # logging.warning('Cache Status View %s' % (q.get_cache_status()))
        return_data = {
            "data":
                {"columns": response_data.pop(0), "data": response_data},
            "time_elapsed": round(time_elapsed, 2),
            "cached": q.get_cache_status(),
            "error": False}
    except Exception, e:
        # logging.warning(str(sys.exc_info()) + str(e))
        logging.warning(traceback.format_exc())
        return_data = {
            "data": str(e),
            "time_elapsed": 0,
            "cached": False,
            "error": True}
    return HttpResponse(
        json.dumps(return_data, cls=DateTimeEncoder),
        content_type="application/json")


@login_required
def query_view(request, query_ids, type='query', **kwargs):
    query_id_array = query_ids.split(',')
    # TODO filter to make sure only this applies to queries which exist
    query_list = [m for m in models.Query.objects.filter(
        id__in=query_id_array)]
    # Get Favorites
    # TODO get rid of copy paste job here with queries
    user = User.objects.get(username=request.user)
    query_favorites = favit.models.Favorite.objects.for_user(
        user, model=models.Query)
    query_fav_dict = dict([(i.target_object_id, i) for i in query_favorites])

    replacement_dict = {}
    json_get = {}
    for q in query_list:
        if q.id in query_fav_dict:
            setattr(q, 'fav', True)
        else:
            setattr(q, 'fav', False)

        lq = query.LoadQuery(
            query_id=q.id,
            user=request.user,
            parameters=request.GET.dict())
        ml = machine_learning_model.objects.filter(query=q.id)
        if ml is not None:
            setattr(q, 'ml', ml)
        lq.prepare_query()
        q.query_text = lq.query.query_text
        for k, v in lq.target_parameters.iteritems():
            # This dict has target, replacement, and data_type
            replacement_dict[k] = v
            json_get[v['search_for']] = v['replace_with']
        # Add on requests for Cacheable / other needed parameters
        json_get_extra_array = ['cacheable']
        for k in json_get_extra_array:
            if request.GET.get(k, None) is not None:
                json_get[k] = request.GET.get(k)
        d = {
            'query_list': query_list,
            'replacement_dict': replacement_dict,
            'json_get': json.dumps(json_get),
            'type': type
        }
        d.update(**kwargs)
        # logging.warning(d)
    return render_to_response(
        'website/query.html',
        d,
        context_instance=RequestContext(request))


@login_required
def query_name(request, query_names):
    query_name_array = query_names.split(',')
    queries = models.Query.objects.filter(title__in=query_name_array)
    query_list_string = ','.join([str(q.id) for q in queries])
    return query_view(request, query_list_string, 'query')


@login_required
def dashboard(request, dashboard_id):
    # First find all the queries, then run it as a list of queries
    dashboard_query_list = models.DashboardQuery.objects.filter(
        dashboard_id=dashboard_id).order_by('order')
    dashboard_data = models.Dashboard.objects.filter(
        id=dashboard_id).first()
    query_id_array = []
    for q in dashboard_query_list:
        query_id_array.append(str(q.query_id))
    query_list_string = ','.join(query_id_array)
    return query_view(
        request,
        query_list_string,
        'dashboard',
        dashboard=dashboard_data)


@staff_member_required
def query_interactive(request):
    # Render empty page for users to add data to
    db_list = models.Db.objects.all()
    return render_to_response(
        'website/query_interactive.html',
        {'db_list': db_list},
        RequestContext(request))


@staff_member_required
def query_interactive_api(request):
    # Take Query, Database, and Pivot
    # Create DataManager, run and return as JSON schema
    try:
        query_text = request.POST['query_text']
        db = models.Db.objects.filter(id=request.POST['db']).first()
        pivot = request.POST.get('pivot', '').lower() == 'true'
        cumulative = request.POST.get('cumulative', '').lower() == 'true'
        start_time = time.time()
        md = query.ManipulateData(
            query_text=query_text,
            db=db,
            user=request.user,
            cacheable=False,
        )
        md.prepare_safety()
        md.run_query()
        if pivot:
            md.pivot()
        if cumulative:
            md.cumulative()
        md.pandas_to_array()
        response_data = md.data_array  # numericalize_data_array()
        time_elapsed = time.time() - start_time  # TODO get rid of this
        return_data = {
            "data": {
                "columns": response_data.pop(0),
                "data": response_data
            },
            "time_elapsed": time_elapsed,
            "error": False}
    except Exception, e:
        logging.warning(traceback.format_exc())
        return_data = {
            "data": str(e),
            "time_elapsed": 0,
            "error": True}
    return HttpResponse(json.dumps(return_data, cls=DateTimeEncoder),
                        content_type="application/json")


@staff_member_required
def database_explorer(request):
    # Render empty page for users to add data to
    db_list = models.Db.objects.all()
    return render_to_response(
        'website/database_explorer.html',
        {'db_list': db_list},
        RequestContext(request))


@staff_member_required
def database_explorer_api(request):
    # Get DB
    try:
        con_id = request.GET.get('con_id')  # connection id is needed
        db_id = request.GET.get('db_id', None)  # Database's database or none
        table_id = request.GET.get('table_id', None)  # table name , or none
        # Get DB Type
        con = models.Db.objects.filter(id=con_id).first()

        # Switch in database Type
        # TODO generalize this as it will be copy-pasta soon
        if con.type == 'MySQL':
            dmm = sql_manager.MySQLManager(con, request)
        elif con.type == 'Postgres':
            dmm = sql_manager.PSQLManager(con, request)
        else:
            raise ValueError("""Database cannot be explorered yet.
                    Only supported types are MySQL &Postgres""")

        # Get proper response data
        if db_id is None:
            dmm.find_database()
        elif table_id is None:  # Show tables if table is none
            dmm.show_tables(db_id)
        elif table_id is not None:
            dmm.describe_table(db_id, table_id)
        else:
            raise ValueError("""ERROR: con_id is needed,
                    db_id needed for to produce table list,
                    table_id needed to procude column list""")

        dmm.run_query()
        response_data = dmm.RQ.data_array  # numericalize_data_array()
        return_data = {
            "data":
            {
                "columns": response_data.pop(0),
                "data": response_data
            },
            "error": False}
        return HttpResponse(
            json.dumps(return_data, cls=DateTimeEncoder),
            content_type="application/json")
    except Exception:
        logging.warning(traceback.format_exc())
        return_data = {
            "data": str(traceback.format_exc()),
            "time_elapsed": 0,
            "error": True}
    return HttpResponse(

templates/website/_favorite_button.html
<a object_id="{{ query.id }}" target_model="website.Query" href="javascript:" class="fa {{ query.fav|yesno:"fa-star,fa-star-o" }}"></a>

templates/website/base.html
{% load url from future %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'fav.ico' %}">

    <title>{% block title %}(no title){% endblock %}</title>

    {% block style %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/sticky-footer-navbar.css' %}">
    <link rel="stylesheet" href="{% static 'datatables-bootstrap/dataTables.bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'DataTables-1.10.7/extensions/TableTools/css/dataTables.tableTools.css' %}">
    <link rel="stylesheet" href="{% static 'css/warning_box.css' %}">
    <!--<link rel="stylesheet" href="{% static 'css/star.css' %}">-->
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    {% endblock %}

  </head>
  <body {% block body %}{% endblock %}>
    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'website:home' %}">SQLViz<sup><small>beta</small></sup></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          {% block links %}
            {% url 'website:home' as home %}
            {% url 'website:query_interactive' as query_interactive %}
            {% url 'website:query' as query_url %}
            {% url 'ml:index' as ml_index %}


            <li 
            {% if request.path = home %}
              class="active"
            {% endif %}>
              <a href="{% url 'website:home' %}">Home</a>
            </li>
            {% if user.is_staff %}
              <li>
                <a href="{% url 'admin:index' %}">Admin</a>
              </li>
              {% if type = 'query' %}
                <li class='active'>
                  <a href="{% url 'admin:website_query_change' query_list.0.id %}">Edit</a>
                </li>
              {% elif type = 'dashboard' %}
                <li class='active'>
                  <a href="{% url 'admin:website_dashboard_change' dashboard.id %}">Edit</a>
                </li>
              {% else %}
                <li>
                  <a href="{% url 'admin:index'%}">Edit</a>
                </li>
              {% endif %}
              
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li role="presentation"
                  {% if request.path = query_interactive %}
                  class="active"
                  {% endif %}>
                  <a role="menuitem" tabindex="-1" href="{% url 'website:query_interactive' %}">Interactive Mode</a>
                </li>
                <li role="presentation"
                  {% if request.path = ml_index %}
                    class="active"
                  {% endif %}>
                <a role="menuitem" tabindex="-1" href="{% url 'ml:index' %}">Machine Learning</a></li>
              </ul>
            </li>
          </span>
            {% endif %}
          {% endblock links %}
          </ul>
          {% if user.is_authenticated %}
            <form class="navbar-form navbar-left" action='{% url 'haystack_search' %}' method = 'get'>
              <input class='form-control' type = 'text' name = 'q' id = 'q' value = '{{request.GET.q}}'></input>
              <button type = "submit" class = "btn btn-success">Search</button>
            </form>
          {% endif %}
          <ul class="nav navbar-nav navbar-right">
            {% if user.username %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  Welcome,
                  <strong>{% firstof user.get_short_name user.get_username %}</strong>.
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    {% if messages %}
      <div class="container">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
        </div>
        {% endfor %}
      </div>
    {% endif %}
    <div class="container-fluid">
        {% block main %}(no content){% endblock main %}
    </div>
    <div class="footer">
      <div class="container">
        <p class="text-muted">
          <a href="http://sqlviz.com">Copyright 2015 Matthew Feldman, Trey Hunner</a>
        </p>
      </div>
    </div>
    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"  type="text/javascript" charset="utf-8"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'DataTables-1.10.7/media/js/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables-bootstrap/dataTables.bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'DataTables-1.10.7/extensions/TableTools/js/dataTables.tableTools.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/favorites.js' %}"  type=" text/javascript" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'ace-builds/src/ace.js' %}"  type="text/javascript" charset="utf-8"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-55739949-1', 'auto');
      ga('send', 'pageview');
    </script>
    {% endblock javascript %}
  </body>
</html>

templates/website/query.html
{% extends 'website/base.html' %}

{% load staticfiles %}
{% load comments %}

{% block title %} 
  {% if query_list %}
    {% for query in query_list %}  
      {{query.title}}
    {% endfor %}
  {% else %}
      No Matched Query
  {% endif %}  
{% endblock %}

{% block body %}
  data-spy="scroll" data-target="#myScrollspy"
{% endblock %}


{% block main %}
  <div class='col-xs-9 content' role='main'>
  {% if dashboard %}
    <section class='well' id='dash_data'>

      <h2><a object_id ='{{dashboard.id}}' target_model='website.Dashboard' href='javascript:' class='fa {% if dashboard.fav %}fa-star{% else %}fa-star-o{% endif %}'>
      </a>{{dashboard.title}}</h2>
    <div class='inline'>
      <p>
        {{dashboard.description}}
        {{dashboard.description_long}}
      </p>
    </div>
    </section>
  {% endif %}

  {% if query_list %}
    {% for query in query_list %}    
      <section class='well' id='div_{{query.id}}'>
        <h2>
          <div class='inline'>
            {% include "website/_favorite_button.html" %}
            </a>
            {{query.title}}
          </div>
        </h2>
        <div id="waiting_{{query.id}}">
          <i class="fa fa-circle-o-notch fa-spin"></i>
        </div>
        <div class='hide_{{query.id}}'>
          <div id="error_{{query.id}}" class = "alert alert-error alert-block">
            <pre></pre>
          </div>
        </div>
        <div role="tabpanel" id="ready_{{query.id}}">
          <!-- Nav tabs -->
          <ul class="nav nav-pills" role="tablist">
            <li role="presentation" class="active">
              <a href="#description_{{query.id}}" aria-controls="settings" role="tab" data-toggle="tab">
                Description
              </a>
            </li>
            {% if query.chart_type != "None" %}
              <li role="presentation" class="hide">
                <a href="#graph_{{query.id}}" aria-controls="graph_{{query.id}}" role="tab" data-toggle="tab">
                  Graph
                </a>
              </li>
            {% endif %}
            <li role="presentation" class="hide"><a href="#tab_table_{{query.id}}" aria-controls="tab_table_{{query.id}}" role="tab" data-toggle="tab">Table</a></li>
            <li role="presentation" class="hide"><a href="#pivot_{{query.id}}" aria-controls="pivot_{{query.id}}" role="tab" data-toggle="tab">Pivot</a></li>
            <li role="presentation" class="hide"><a href="#ml_{{query.id}}" aria-controls="settings" role="tab" data-toggle="tab">Regression</a></li>
          </ul>
        </div>
          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane" id="graph_{{query.id}}">
              <div id='chart_{{query.id}}'></div>
            </div>
            <div role="tabpanel" class="tab-pane" id="tab_table_{{query.id}}">
              <div id='div_table_{{query.id}}'></div>
            </div>
            <div role="tabpanel" class="tab-pane" id="pivot_{{query.id}}">
              <div id='div_pivot_{{query.id}}'></div>
            </div>

            <div role="tabpanel" class="tab-pane" id="ml_{{query.id}}">
              <div id='ml_section'>
                <h3>Machine Learning Models</h3>
                {% if query.ml %}
                  {% for ml_i in query.ml %}
                    <h4> Static Models</h4>
                    <button type="submit" id="ml_{{ml_i.id}}" class="btn btn-info">
                      {{ml_i}}
                    </button>
                  {% endfor %}
                {% endif %}
                <h4> ad hoc model</h4>
                  <form id='ml_adhoc_{{query.id}}' class="input-group">
                    <select class="form-control" id="column_names_{{query.id}}">
                    </select>
                    <select class="form-control" id="model_type_{{query.id}}">
                      <option value="linear">Linear Regression</option>
                      <option value="logistic">Logistic Regression</option>
                      <option value="tree">Decision Tree</option>
                      <option value="kmeans">K-Means</option>
                    </select>
                    <button type="submit" class="btn btn-info">Run ML Model</button>
                  </form>
                  <pre id='ml_output_{{query.id}}' class='hide'></pre>
                </div> 
              </div>
              <div role="tabpanel" class="tab-pane active" id="description_{{query.id}}">

                <ul>
                  <li>{{query.description}}</li>
                  {% if user.is_staff %}
                    <form action="{% url 'admin:website_query_change' query.id %}">
                      <button type="submit" class="btn btn-info">
                        Edit
                      </button>
                    </form>
                  {% endif %}
                  <li><a href="mailto:{{query.owner.email}}">{{query.owner}}</a></li>
                  {% if query.description_long %}
                    <li>Description Long: {{query.description_long}}</li>
                  {% endif %}
                  <li>Query Text:
                    <div id='sql_{{query.id}}'>
                      <pre>{{query.query_text}}</pre>
                    </div>
                  </li>
                  <li>Query Creation: {{query.create_time}}</li>
                  <li>Query Last Modified: {{query.modified_time}}</li>
                  <li>Database: {{query.db}}</li>
                  <!--<li id='execution_info_{{query.id}}'></li>-->
                  {% include "website/_tags.html" %}
                  {% render_comment_list for query %}

                  {% if user.is_staff %}
                    {% get_comment_form for query as form %}
                      <div class="form-group">
                        <form action="{% comment_form_target %}" method="POST">

                        {% csrf_token %}
                        <input type="text" class="form-control" id="id_comment" maxlength="3000" name="comment" placeholder="Comment Here">
                        {{ form.content_type }}
                        {{ form.object_pk }}
                        {{ form.timestamp }}
                        {{ form.security_hash }}
                        <input type="hidden" name="next" value="{% url 'website:query' query.id %}" />
                      </br>
                        <input type="submit" class="btn btn-default" value="Add comment" id="id_submit" />
                    </form>
                    </div>
                {% endif %}

                  
                </ul>
              </div>
            </div>
      </section>
      
    {% endfor %}
  {% else %}
      <h3 class='label-danger'>No Queries found with that namespace or permission denied.  Are you sure it is there?</h3>
  {% endif %}
  {% if replacement_dict %}
    <section class='well' id='parameters_insert'>
      <h3>Re-Run with Parameters</h3>
      <form action ='{{request.path}}' method='GET'>
        {% for key, default_dict in replacement_dict.items %}
          {% if default_dict.data_type == 'Date' %}
            {# DATEPICKER #}
            <p> {{default_dict.search_for}} 
            <input type="text" class="" value="{{default_dict.replace_with}}" id="selector_{{default_dict.search_for}}" label="{{default_dict.search_for}}"
            name = "{{default_dict.search_for}}"
            >
            </p>
          {% elif default_dict.data_type == 'Numeric' %}
            {# NUMERIC #}
            <p> {{default_dict.search_for}}
              <input type="range" class="" value="{{default_dict.replace_with}}" min=-1000 max=1000 id="selector_{{default_dict.search_for}}" label="{{default_dict.search_for}}" name = "{{default_dict.search_for}}">
            </p>
          {% else %}
            {# STRING #}
            <p> {{default_dict.search_for}}
              <input type="text" class="" value="{{default_dict.replace_with}}" id="selector_{{default_dict.search_for}}" label="{{default_dict.search_for}}" name = "{{default_dict.search_for}}">
            </p>
          {% endif %}
        {% endfor %}
        <input type="submit" class='btn btn-primary' value="Submit"/>
        </form>
      </section>
    {% else %}
      No Defaults Found
    {% endif %}
  </div>
  {% if query_list %}
    <div class="col-xs-3 hidden-sm hidden-xs" id="myScrollspy">
      <ul class="nav nav-tabs nav-stacked affix-top" data-spy="affix" data-offset-top="200">
        {% for query in query_list %}
          <li>
            <a href="#div_{{query.id}}"
            {% if query == query_list|first %}
              class='active'
            {% endif %}
            >{{query.title}}</a>
          </li>
        {% endfor %}
        {% if replacement_dict %}
          <li>
            <a href="#parameters_insert">Parameters</a>
          </li>
        {% endif %}
      </ul>
    </div>
  {% endif %}
{% endblock %}

{% block style %}
{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'pivottable/pivot.css' %}"></link>
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav_stuff.css' %}"></link>
{% endblock %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/make_chart.js' %}"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<!-- For country charts -->
<script type="text/javascript" src="{% static 'Highcharts/js/highcharts.src.js' %}"></script>
<script type="text/javascript" src="{% static 'Highmaps/modules/map.js' %}"></script>
<script type="text/javascript" src="{% static 'Highmaps/modules/exporting.js' %}"></script>
<script src="{% static 'js/world-highres.js' %}"></script>
<script src="{% static 'js/website_query.js' %}"></script>
<script type="text/javascript" src="{% static 'pivottable/pivot.js' %}"></script>
<script>
  make_favorites('{% url 'favs:add' %}','{% url 'favs:remove' %}');
</script>
{% if query_list %}
  {% for query in query_list %}
    <script>
    display_data({{query.id}}, '{% url "website:query_api" query.id %}',  {{json_get|safe}}, '{{query.hide_table}}', '{{query.chart_type}}', '{{query.title}}', '{{query.stacked}}', '{{query.log_scale_y}}', '{{query.graph_extra|safe}}')
    </script>
    <script>
      $(document).ready(function(){
        $( "#ml_adhoc_{{query.id}}").submit(function( event ) {
          event.preventDefault();
          send_data_ml_adhoc('{{query.id}}', '{% url "ml:build_model_adhoc" %}','ml_output_{{ml_i.id}}');
        });
      });
    </script>
    {% if query.ml %}
      {% for ml_i in query.ml %}
        <script>
          make_adhoc_model({{ml_i.id}},
              '{% url "ml:build_model" ml_i.id  %}',
              {{json_get|safe}}, {{query.id}});
        </script>
      {% endfor %}
    {% endif %}
  {% endfor %}
{% endif %}
<script>
  make_date_picker('{{default_dict.search_for}}');
</script>
{% endblock javascript %}